<template>
    <div class="row q-gutter-sm items-center">
    <q-select class="col " style="width: 200px" standout v-model="model" :options="options" label="Vald Sport" bg-color="white"></q-select>

    <q-btn color="white" text-color="black" label="Standard" @click="getAktiviteter()"/>

    <q-input class="col " filled v-model="date" mask="date" :rules="['date']" bg-color="white" style="margin-top:28px">
        <template v-slot:append>
        <q-icon name="event" class="cursor-pointer">
            <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
            <q-date v-model="date">
                <div class="row items-center justify-end">
                <q-btn v-close-popup label="Close" color="primary" flat></q-btn>
                </div>
            </q-date>
            </q-popup-proxy>
        </q-icon>
        </template>
    </q-input>

    <q-input class="col" outlined v-model="model" label="Sök Stad" bg-color="white"></q-input>

    <q-btn class="col-2" :loading="loading1" color="secondary" @click="simulateProgress(1)" label="SÖK!" style="height:54px"></q-btn>
    </div>
</template>

<script>
import { db } from '../boot/firebase.js'

export default {
  computed: {
    // a computed getter
    getAktiviteter () {
      // `this` points to the vm instance
      const returnAktiviteter = []
      const arrayAktiviti = this.aktiv
      for (const sport in arrayAktiviti) {
        console.log(sport)
      }
      return returnAktiviteter
    }
  },

  data () {
    return {
      aktiv: [],
      loading1: false,
      date: '2019/02/01',
      model: null,
      options: [
        'Tennis', 'Gold', 'Prinskorv', 'Penis', 'KastMedLitenApa'
      ],
      info: {
        info1: 'Vi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT'
      }
    }
  },
  firestore: {
    aktiv: db.collection('sporter')
  }
}
</script>

<style>

</style>
