<template>
    <div class="row q-gutter-sm items-center">
    <q-select class="col " style="width: 200px" standout v-model="model" :options="aktiv" option-value="id" option-label="sport" label="Vald Sport" bg-color="white"></q-select>

    <q-input class="col " filled v-model="date" mask="date" :rules="['date']" bg-color="white" style="margin-top:28px">
        <template v-slot:append>
        <q-icon name="event" class="cursor-pointer">
            <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
            <q-date v-model="date">
                <div class="row items-center justify-end">
                <q-btn v-close-popup label="Close" color="primary" flat></q-btn>
                </div>
            </q-date>
            </q-popup-proxy>
        </q-icon>
        </template>
    </q-input>
      <q-select
        filled
        v-model="searchInput"
        clearable
        use-input
        hide-selected
        fill-input
        input-debounce="300"
        label="Focus after filtering"
        :options="cities"
        option-value="id"
        option-label="city"
      >
        <template v-slot:no-option>
          <q-item>
            <q-item-section class="text-grey">
              No results
            </q-item-section>
          </q-item>
        </template>
      </q-select>

    <q-input v-model="searcher" placeholder="searsh box" />

    <q-btn class="col-2" :loading="loading1" color="secondary" label="SÖK!" style="height:54px" @click="sendValues"></q-btn>

    <searchResult :result="aktiv"></searchResult>

    </div>
</template>

<script>
import { db } from '../boot/firebase.js'
import searchResult from '../components/searchResult.vue'

export default {
  data () {
    return {
      stader: [],
      aktiv: [],
      finalSulution: [],
      search: '',
      cities: [],
      searcher: '',

      loading1: false,
      test: [{ sport: 'boll', id: 'dsdsd' }, {
        sport: 'tennis', id: 'dasaa'
      }],
      date: '2019/02/01',
      model: null,
      searchInput: null,
      options: [
        'Tennis', 'Gold', 'Prinskorv', 'Penis', 'KastMedLitenApa'
      ],
      info: {
        info1: 'Vi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT'
      }
    }
  },
  firestore: {
    aktiv: db.collection('sporter'),
    cities: db.collection('cities'),
    finalSulution: db.collection('test')
  },
  components: {
    searchResult
  },

  methods: {
    sendValues () {
      console.log(this.aktiv)
      console.log(this.finalSulution)
      console.log('skickar värden')
    }
  },
  computed: {
    drawerState: {
      get () {
        return this.$store.state.showcase.drawerState
      },
      set (val) {
        this.$store.commit('showcase/updateDrawerState', val)
      }
    },
    filterSearch: function () {
      console.log('hejejejeheheheh')
      return ('hej')
    }
  }
}
</script>

<style>

</style>
