<template>
  <q-page class="">
      <q-card class="my-card">
        <q-parallax
          src="https://www.unisport.com/sites/default/files/styles/teaser/public/2019-04/unisport-padel1.jpg?itok=AkKu_7-R"
          :height="300">
          <div class="row q-gutter-sm items-center">
            <q-select class="col " style="width: 200px" standout v-model="model" :options="options" label="Vald Sport" bg-color="white"></q-select>

            <q-input class="col " filled v-model="date" mask="date" :rules="['date']" bg-color="white" style="margin-top:28px">
              <template v-slot:append>
                <q-icon name="event" class="cursor-pointer">
                  <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
                    <q-date v-model="date">
                      <div class="row items-center justify-end">
                        <q-btn v-close-popup label="Close" color="primary" flat></q-btn>
                      </div>
                    </q-date>
                  </q-popup-proxy>
                </q-icon>
              </template>
            </q-input>

            <q-input class="col" outlined v-model="text" label="Sök Stad" bg-color="white"></q-input>

            <q-btn class="col-2" :loading="loading1" color="secondary" @click="simulateProgress(1)" label="SÖK!" style="height:54px"></q-btn>

          </div>
        </q-parallax>
      </q-card>

    <p class=" q-ml-xl q-mr-xl q-pa-xl">{{info.info1}}</p>
    <bottom-information></bottom-information>
  </q-page>
</template>

<script>
import BottomInformation from '../components/BottomInformation.vue'
export default {
  name: 'PageIndex',
  components: {
    BottomInformation
  },
  methods: {
    simulateProgress (number) {
      // we set loading state
      this[`loading${number}`] = true
      // simulate a delay
      setTimeout(() => {
        // we're done, we reset loading state
        this[`loading${number}`] = false
      }, 3000)
    }
  },
  data () {
    return {
      loading1: false,
      date: '2019/02/01',
      model: null,
      options: [
        'Tennis', 'Gold', 'Prinskorv', 'Penis', 'KastMedLitenApa'
      ],
      info: {
        info1: 'Vi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROTVi är sportit och vi älskar inte grönsaker speciellt inte MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT MOROT'
      }
    }
  }
}// importerat bottominformationcomponenten
</script>
